### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by codeyash** [abluescarab/ListBoxTabs#1]
Please let us know.

**Comment by abluescarab** [comment]
The license is the GPL v3.0. The code itself can be modified, but must remain free and open source. Projects using ListBoxTabs, however, can be commercial.

**Comment by codeyash** [comment]
Very restrictive for such a simple component. Its a library like code so LGPL makes more sense. MIT or Apache is much better you want your component to be popular. I can't use current licensed code.

Anyways its your code. 

Best of luck :)

**Comment by abluescarab** [comment]
I'll take a look at the other licenses, but I tend to stick to the GPL license as it keeps others from monetizing free software. I'll let you know, but I'm currently out of state and don't have much time to look. 

Thanks for the feedback.
